# DO NOT EDIT! Automatically generated by scripts/generate_providers_and_account_vars.py
# To Rebuild zz-do-not-modify-providers.tf, execute the generate_providers_and_account_vars GitHub workflow.


provider "aws" {
  alias  = "Prasad-Lab-Env"
  region = "us-east-1"
  assume_role {
    role_arn = "arn:aws:iam::867346621613:role/github-assume-role-rvm"
  }
}

