# DO NOT EDIT! Automatically generated by scripts/generate_providers_and_account_vars.py
# To rebuild variables-accounts.tf, execute the generate_providers_and_account_vars GitHub workflow.


variable "account_Prasad-Lab-Env" {
  type    = string
  default = "867346621613"
}

